<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>IndustrialProtocolAssistant.Drivers</RootNamespace>
    <AssemblyName>IndustrialProtocolAssistant.Drivers</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\IndustrialProtocolAssistant.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="4.3.1.873" />
    <PackageReference Include="NModbus" Version="3.0.81" />
    <PackageReference Include="S7netplus" Version="0.14.0" />
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client" Version="1.4.372.81" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="IndustrialProtocolAssistant.Tests" />
  </ItemGroup>
</Project>
