<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>IndustrialProtocolAssistant.Storage</RootNamespace>
    <AssemblyName>IndustrialProtocolAssistant.Storage</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\IndustrialProtocolAssistant.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.10" />
  </ItemGroup>
</Project>
